// backend/src/middlewares/validateMiddleware.js



const { validationResult } = require('express-validator');

/**
 * Middleware that checks for validation errors generated by express-validator chains.
 * If errors are found, it stops the request and returns a 400 Bad Request.
 * @module validate
 */
const validate = (req, res, next) => {
    const errors = validationResult(req);

    if (!errors.isEmpty()) {
        // Improvement: Return a unified error format (success: false) for consistency
        return res.status(400).json({ 
            success: false,
            message: 'Validation failed. Check error details.',
            errors: errors.array().map(error => ({
                field: error.path, // Use 'path' instead of 'param' for newer express-validator
                message: error.msg
            }))
        });
    }
    
    // If no validation errors, proceed to the next middleware/controller
    next();
};

module.exports = validate;